1. Crea un array de una única fila con 15 columnas cuyos elementos sean todo unos y guárdalo en una variable.

In [1]:
import numpy

In [ ]:
array1 = numpy.ones((15), dtype = int)
array1

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

2. A continuación, modifica los valores de los 10 últimos elementos, a los que debes asignar el valor 5.

In [ ]:
array1[-10:] = 5
array1

array([1, 1, 1, 1, 1, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

3. Finalmente, utiliza la función arrange para modificar el resto de elementos del array para que vayan adquiriendo como valores los múltiplos de  de manera incremental.

In [ ]:
trocito = array1[0:5]
trocito[0]= 7
trocito[1:] = numpy.arange(14, 36, 7)
array1

array([ 7, 14, 21, 28, 35,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5])

4. Carga en una variable el array del fichero de texto manipDatosEstruc_actividad1_1.txt del Campus Virtual


In [3]:
array2 = numpy.loadtxt("/content/manipDatosEstruc_actividad1_1.txt", dtype=float, delimiter=',')
array2

array([0.52266931, 0.20060662, 0.29290083, 0.80499206, 0.7535142 ,
       0.50890023, 0.6370857 , 0.04895814, 0.5992934 , 0.03191176,
       0.50051748, 0.46501826, 0.53944828, 0.73162648, 0.65282133,
       0.81857564, 0.45498185, 0.78779364, 0.38606455, 0.55803441,
       0.67982107, 0.86557797, 0.64690177, 0.48227321, 0.45627267,
       0.86186496, 0.60046005, 0.8530146 , 0.72777678, 0.23766215,
       0.18755646, 0.32247517, 0.90196779, 0.53693843, 0.28032629,
       0.26040698, 0.32143603, 0.84376252, 0.92588614, 0.87223793,
       0.10355453, 0.23537035, 0.88608701, 0.1977346 , 0.1275113 ,
       0.68570142, 0.99647574, 0.12836516, 0.0676506 , 0.09447244,
       0.72840322, 0.25671293, 0.04171931, 0.17948247, 0.91679496,
       0.258496  , 0.00734302, 0.39529027, 0.27707908, 0.51952908,
       0.40038924, 0.36101664, 0.92429448, 0.62407357, 0.78628573,
       0.39049457, 0.78655648, 0.45978434, 0.99278192, 0.87567674,
       0.93897748, 0.39401604, 0.36604832, 0.80635351, 0.05665

5. Calcula la media de los elementos

In [ ]:
media = numpy.mean(array2)
media

0.5125855079

6. Obtén un array con los elementos superiores o iguales a la media

In [ ]:
mayores_media = array2[array2 >= media]
mayores_media

array([0.52266931, 0.80499206, 0.7535142 , 0.6370857 , 0.5992934 ,
       0.53944828, 0.73162648, 0.65282133, 0.81857564, 0.78779364,
       0.55803441, 0.67982107, 0.86557797, 0.64690177, 0.86186496,
       0.60046005, 0.8530146 , 0.72777678, 0.90196779, 0.53693843,
       0.84376252, 0.92588614, 0.87223793, 0.88608701, 0.68570142,
       0.99647574, 0.72840322, 0.91679496, 0.51952908, 0.92429448,
       0.62407357, 0.78628573, 0.78655648, 0.99278192, 0.87567674,
       0.93897748, 0.80635351, 0.55435037, 0.64388241, 0.85259588,
       0.82736171, 0.61412489, 0.94184994, 0.73727697, 0.91261282,
       0.58848056, 0.75564679, 0.97745411, 0.55402065])

7. Carga en una variable el array del fichero de texto manipDatosEstruc_Actividad1_2.txt del Campus Virtual. Contiene la media de un alumno en cada uno de los cuatro cursos del grado que ha cursado

In [4]:
notas = numpy.loadtxt("/content/manipDatosEstruc_actividad1_2.txt", dtype=float, delimiter=',')
notas

array([7.2, 5.2, 8.1, 9.4])

8. Obtén un array que indique los cursos en los que su nota ha sido superior a 7. El resultado debe ser [1,3,4]. Para ello, debes crear un array con los índices de cada curso con la función arange (es decir, el array[1,2,3,4]) y acceder a él mediante un array de booleanos creado anteriormente.

In [5]:
notas_superiores_7 = notas >7
indices_cursos = numpy.arange(1, len(notas) + 1)
cursos_mas_7 = indices_cursos [notas_superiores_7]
cursos_mas_7

array([1, 3, 4])

9. Obtén un array que indique los cursos en los que su nota ha sido inferior a la media. El resultado debe ser [1,2]. Debes seguir la misma estrategia que en el ejercicio anterior.

In [6]:
media_cursos = numpy.mean(notas)
notas_menores_media = notas < media_cursos
cursos_menos_media = indices_cursos[notas_menores_media]
cursos_menos_media

array([1, 2])

10. Calcula cuál es el curso en el que la media del alumno se aproxima más a la media obtenida en la carrera.

In [7]:
diferencias = numpy.abs(notas - media_cursos)
curso_aprox_media = numpy.argmin(diferencias) + 1
curso_aprox_media

1